### PR TITLE
better imports

### PR DESCRIPTION
**Pull request by mafineeek**
repaired imports plz merge

### CODE REVIEW

**Comment by tfo-dot** [comment]
This code still doesn't meet our requirements according to code styling. Thanks for contributing to the corddis GitHub repository.

**Comment by mafineeek** [comment]
so tell me what's wrong, your coding style is based on else if XD?

**Comment by mafineeek** [comment]
@ZiomaleQ

**Comment by indexerrowaty** [comment]
VERY UNPINDOREK

**Comment by tfo-dot** [comment]
> so tell me what's wrong, your coding style is based on else if XD?

There is no such thing as `else if XD`

**Comment by indexerrowaty** [comment]
He wants spaces instead of tabs. Change that and I think you are good to go.

**Comment by indexerrowaty** [comment]
merge

**Comment by indexerrowaty** [comment]
Nah jk

**Pull request merged**
